add tests for callSet Add & Remove
Adds tests to complement the changes introduced in #107.

I validated that these tests would have caught the ordering bug fixed by
PR #107 by reverting the change locally:

revert diff:
```diff
diff --git a/gomock/callset.go b/gomock/callset.go
index 05d6fa2..c652f42 100644
--- a/gomock/callset.go
+++ b/gomock/callset.go
@@ -44,7 +44,11 @@ func (cs callSet) Remove(call *Call) {
        for i, c := range sl {
                if c == call {
                        // maintain order for remaining calls
-                       methodMap[call.method] = append(sl[:i], sl[i+1:]...)
+                       // methodMap[call.method] = append(sl[:i], sl[i+1:]...)
+                       if len(sl) > 1 {
+                               sl[i] = sl[len(sl)-1]
+                       }
+                       methodMap[call.method] = sl[:len(sl)-1]
                        break
                }
        }
```

test output:
```
=== RUN   TestCallSetAdd
--- PASS: TestCallSetAdd (0.00s)
=== RUN   TestCallSetRemove
--- FAIL: TestCallSetRemove (0.00s)
	callset_test.go:61: found call 1 after call 9
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 2 after call 8
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 7 after call 8
	callset_test.go:61: found call 3 after call 7
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 7 after call 8
	callset_test.go:61: found call 6 after call 7
	callset_test.go:61: found call 4 after call 6
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 7 after call 8
	callset_test.go:61: found call 6 after call 7
	callset_test.go:61: found call 5 after call 6
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 7 after call 8
	callset_test.go:61: found call 6 after call 7
	callset_test.go:61: found call 8 after call 9
	callset_test.go:61: found call 7 after call 8
	callset_test.go:61: found call 8 after call 9
```